trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos'

variables:
  buildDir: 'app/build/outputs/apk/release'

jobs:
- job: Build
  displayName: "Build Android APK"
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Use Python 3.x'

    - task: Gradle@2
      displayName: 'Build Release APK'
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        options: 'clean'
        tasks: 'assembleRelease'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish APK Artifact'
      inputs:
        PathtoPublish: '$(buildDir)'
        ArtifactName: 'apk-release'